#!/bin/bash

export BASE_WORK_DIR="/Users/leonardoriviere/Documents/Work"
export PATH=$PATH:/Applications/MAMP/Library/bin
#export ANDROID_HOME=/Users/leonardoriviere/Library/Android/sdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
export ANDROID_HOME=/usr/local/Caskroom/android-sdk/3859397,26.0.1
#export PATH=$ANDROID_HOME/platform-tools:$PATH
#export PATH=$ANDROID_HOME/tools:$PATH
#export ANDROID_HOME=/Users/leonardoriviere/Library/Android/sdk
#export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# Colored ls
source $(dirname $(gem which colorls))/tab_complete.sh

# USEFUL COMMANDS
alias mysql="/Applications/MAMP/Library/bin/mysql --host=localhost -uroot -proot"
alias ls="colorls"
alias lc='ls -lA --sd'
alias l="ls -lt"
alias la="ls -lta"
alias ..="cd .."
alias cd..="cd .."
alias g="git"
alias repo='cd $BASE_WORK_DIR'
alias lg='cd $BASE_WORK_DIR/LG/escribehost'
alias inm='cd $BASE_WORK_DIR/Inmediative'
alias resetdock="osascript -e 'quit application \"Dock\"'"
alias resetaudio="sudo killall coreaudiod"

alias prompt='cd "$BASH_PROFILE_HOME"'
alias edit='atom "$BASH_PROFILE_HOME"'

# GIT COMMANDS
alias st='git status'
alias br='git branch'
alias ci='git commit'
alias co='git checkout '
alias gk='gitk --all&'
alias gskip='git update-index --skip-worktree'
alias gnoskip='git update-index --no-skip-worktree'
alias css='cd app/tools && ./compress_css.pl && cd -'
#alias gh="open `git remote -v | grep fetch | awk '{print $2}' | sed 's/git@/http:\/\//' | sed 's/com:/com\//'`| head -n1"
alias reset='git stash apply'
alias revert='git reset HEAD~1'
alias cleanbranches='git branch | grep -v "master" | grep -v "esh-develop" | grep -v "development" | xargs -n 1 git branch -D'
alias localprune='git branch | grep -v "development" | grep -v "master" | xargs git branch -D'
alias configaliases="git config alias.ci commit && git config alias.co checkout && git config alias.br branch && git config alias.st status && git config alias.cma 'commit -a -m' && git config alias.cp cherry-pick"
alias pccount="git rev-list --count develop..HEAD"

# Custom
#alias cpconfig = 'lg | .. | cp -Rf escribehost-idea/runConfigurations/* escribehost/.idea/runConfigurations/.'

function port(){
    echo "Checking for listeners in port $@ ...";
    lsof -w -n -i tcp:"$@";
}

function showenv(){
  echo "·········································"
  echo "· Environment variables containing $1"
  echo "·········································"
  echo ""
  printenv | grep $1
}

function got(){
  git checkout develop;
  echo " -> Fetching new branches ...";
  git fetch origin;
  echo " -> Checking out $@ ...";
  git checkout -b "$@" origin/"$@";
  echo " -> Pulling latest changes from origin/$@ ...";
  git pull origin "$@";
}

function glog(){
  git log -$@ --oneline
}

function cot(){
  #branch=`git branch | awk '{if ($1 == "*"){print $2}}'`
  branch=`git branch | awk '{if ($1 == "*"){print $2}}' | awk -F '_' '{print $1}'`
  git commit -a -m "$branch - $1"
}

function gpl(){
  git pull --rebase origin `git branch | awk '{if ($1 == "*"){print $2}}'`
}

function gph(){
  git push origin `git branch | awk '{if ($1 == "*"){print $2}}'`
}

function gphf(){
  git push -f origin `git branch | awk '{if ($1 == "*"){print $2}}'`
}

function ga(){
  git commit -a --amend --no-edit
}

function gr(){
  git rebase -i --autosquash HEAD~$1
}

function gc(){
  git add . && git commit -m "-- FIXUP THIS COMMIT --" && git rebase -i HEAD~$1
}

function gwipe(){
  git branch -D $1 && git push origin :$1
}

function gl(){
  git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
}

function glp(){
  git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit -p
}

# Setting git alias for logging
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
