#!/bin/bash

export BASE_WORK_DIR="/Users/leonardoriviere/Documents/Work"
export PATH=$PATH:/Applications/MAMP/Library/bin
#export ANDROID_HOME=/Users/leonardoriviere/Library/Android/sdk
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
export ANDROID_HOME=/usr/local/Caskroom/android-sdk/3859397,26.0.1
#export PATH=$ANDROID_HOME/platform-tools:$PATH
#export PATH=$ANDROID_HOME/tools:$PATH
#export ANDROID_HOME=/Users/leonardoriviere/Library/Android/sdk
#export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
export LG_BASE_DIR=/Users/leonardoriviere/Documents/Work/LG
BLUE='\e[34m'
GREEN='\e[92m'
RED='\033[0;31m'
RED_BG='\e[101m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" 

# Colored ls
# source $(dirname $(gem which colorls))/tab_complete.sh

# USEFUL COMMANDS
alias mysql="/Applications/MAMP/Library/bin/mysql --host=localhost -uroot -proot"
alias ls="colorls"
alias lc='ls -lA --sd'
alias l="ls -lt"
alias la="ls -lta"
alias ..="cd .."
alias cd..="cd .."
alias g="git"
alias repo='cd $BASE_WORK_DIR'
alias lg='cd $BASE_WORK_DIR/Workspace_LG/escribehost'
alias resetdock="osascript -e 'quit application \"Dock\"'"
alias resetaudio="sudo killall coreaudiod"

alias prompt='cd "$BASH_PROFILE_HOME"'
alias edit='atom "$BASH_PROFILE_HOME"'

# GIT COMMANDS
alias st='git status'
alias br='git branch'
alias ci='git commit'
alias co='git checkout '
alias gk='gitk --all&'
alias gskip='git update-index --skip-worktree'
alias gnoskip='git update-index --no-skip-worktree'
alias css='cd app/tools && ./compress_css.pl && cd -'
#alias gh="open `git remote -v | grep fetch | awk '{print $2}' | sed 's/git@/http:\/\//' | sed 's/com:/com\//'`| head -n1"
alias reset='git stash apply'
alias revert='git reset HEAD~1'
alias cleanbranches='git branch | grep -v "master" | grep -v "esh-develop" | grep -v "development" | xargs -n 1 git branch -D'
alias localprune='git branch | grep -v "development" | grep -v "master" | xargs git branch -D'
alias configaliases="git config alias.ci commit && git config alias.co checkout && git config alias.br branch && git config alias.st status && git config alias.cma 'commit -a -m' && git config alias.cp cherry-pick"
alias pccount="git rev-list --count develop..HEAD"

# Custom
#alias cpconfig = 'lg | .. | cp -Rf escribehost-idea/runConfigurations/* escribehost/.idea/runConfigurations/.'

function port(){
    echo "Checking for listeners in port $@ ...";
    lsof -w -n -i tcp:"$@";
}

function showenv(){
  echo "·········································"
  echo "· Environment variables containing $1"
  echo "·········································"
  echo ""
  printenv | grep $1
}

function got(){
  git checkout develop;
  echo " -> Fetching new branches ...";
  git fetch origin;
  echo " -> Checking out $@ ...";
  git checkout -b "$@" origin/"$@";
  echo " -> Pulling latest changes from origin/$@ ...";
  git pull origin "$@";
}

function glog(){
  git log -$@ --oneline
}

function gdiff(){
  git diff HEAD $@
}

function cot(){
  #branch=`git branch | awk '{if ($1 == "*"){print $2}}'`
  branch=`git branch | awk '{if ($1 == "*"){print $2}}' | awk -F '_' '{print $1}'`
  git commit -a -m "$branch - $1"
}

function gpl(){
  git pull --rebase origin `git branch | awk '{if ($1 == "*"){print $2}}'`
}

function gph(){
  git push origin `git branch | awk '{if ($1 == "*"){print $2}}'`
}

function gphf(){
  git push -f origin `git branch | awk '{if ($1 == "*"){print $2}}'`
}

function ga(){
  git commit -a --amend --no-edit
}

function gr(){
  git rebase -i --autosquash HEAD~$1
}

function gc(){
  git add . && git commit -m "-- FIXUP THIS COMMIT --" && git rebase -i HEAD~$1
}

function gwipe(){
  git branch -D $1 && git push origin :$1
}

function gl(){
  git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
}

function glp(){
  git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit -p
}

function gfu(){
  git forgit add
  git forgit fixup
}

# Setting git alias for logging
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"

function esh() {
  echo "ESH - Using ${1} db.properties";
  sudo cp /opt/escribe/conf/db.properties.${1} /opt/escribe/conf/db.properties;
}

function migs() {
  cd $LG_BASE_DIR/escribehost/migrations
  ENV=$1
  echo '';
  echo -e "$BLUE>> Getting all pending migrations for ${NC}${RED_BG}${ENV}${NC}";
  PENDING=`./migrate status --env=$1 | grep ' ...pending... '`;
  AMOUNT=`echo $PENDING | awk NF | wc -l`
  echo -e "$BLUE>> Pending migrations on ${ENV}: ${AMOUNT}";
	if [ $AMOUNT -gt 0 ];
  then
    echo '';
    echo -e $CYAN $PENDING $NC;
    echo '';
    echo -e "$BLUE>> Apply all pending migrations?: [y/n] $NC";
    read apply;
    echo -e $BLUE;
    if [[ $apply =~ 'y|Y' ]];
    then
      ./migrate pending --env=$ENV | grep 'MyBatis Migrations'
      echo -e "$GREEN>> Success. $AMOUNT migrations have been applied. $NC"
    else
      echo -e "$RED>> Aborted. 0 migrations have been applied. $NC"
    fi
  else
    echo -e "$GREEN>> No pending migrations need to be applied. $NC"
  fi
}

backup_remote_branch() {
  # Get the current branch name
  current_branch=$(git rev-parse --abbrev-ref HEAD)

  # Get the current date and time in the format YYYYMMDDHHMM
  timestamp=$(date +'%Y%m%d%H%M')

  # Create the new branch name with the timestamp
  new_branch="${current_branch}_v${timestamp}"

  # Fetch the latest branches from the remote
  git fetch

  # Create and checkout the new branch from the remote branch
  git checkout -b "$new_branch" "origin/$current_branch"

  echo "New branch '$new_branch' created from 'origin/$current_branch'."

  # Checkout back to the original branch
  git checkout "$current_branch"

}

